# Generated by Django 4.1.7 on 2023-04-06 10:19

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_is_buyer_user_is_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=helpers.files.RenameFile(
                    "profile_pics/{instance.user.email}.{extension}"
                ),
            ),
        ),
    ]
