# Generated by Django 3.2.18 on 2023-05-09 18:35

import django.core.validators
from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[helpers.files.ValidateFileSize(max_file_size=5), django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'png', 'jpg'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
