# Generated by Django 4.1.7 on 2023-04-06 10:19

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydocument",
            name="document",
            field=models.FileField(
                upload_to=helpers.files.RenameFile(
                    "property_documents/{instance.property_id}/{instance.document.name}.jpg"
                )
            ),
        ),
        migrations.AlterField(
            model_name="propertygallery",
            name="file",
            field=models.FileField(
                upload_to=helpers.files.RenameFile(
                    "property_gallery/{instance.property_id}/{instance.file.name}.{extension}"
                )
            ),
        ),
    ]
