# Generated by Django 4.1.7 on 2023-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_propertydocument_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydocument",
            name="document",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="propertygallery",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
