# Generated by Django 3.2.18 on 2023-05-12 18:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', validators=[helpers.files.ValidateFileSize(max_file_size=5), django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'png', 'jpg'))]),
            preserve_default=False,
        ),
    ]
